Repository phovea/phovea_security_flask, pull requests merged in 2019-12, with the labels that each got.

#38 Update template files and dependencies
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  buildPython.js
  deploy/docker-compose.partial.yml
  package-lock.json
  package.json
  requirements.txt
  setup.py
  tox.ini
  webpack.config.js
Labels: release: major, type: technical debt

#36 Add I18N support and extract language strings
  package-lock.json
  phovea.js
  phovea_registry.js
  src/LoginMenu.ts
  src/_login_form.html
  src/assets/locales/en/phovea.json
  src/login.ts
  src/phovea.ts
  tsconfig.json
Labels: release: minor, type: feature

#40 Release 3.0.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  buildPython.js
  deploy/docker-compose.partial.yml
  docs/.gitignore
  package-lock.json
  package.json
  phovea.js
  phovea_registry.js
  requirements.txt
  setup.py
  src/LoginMenu.ts
  src/_login_form.html
  src/assets/locales/en/phovea.json
  src/login.ts
  src/phovea.ts
  tox.ini
  tsconfig.json
  webpack.config.js
Labels: release: major
